### ISSUE TITLE
Python3 support broken

### ISSUE THREAD

**Issue by gijzelaerr** [darafferty/LSMTool#10] opened 2017-10-17 14:08 UTC
```
  python3 setup.py test
running test
================================================ test session starts =================================================
platform linux -- Python 3.5.2 -- py-1.4.20 -- pytest-2.5.2
collected 0 items / 1 errors

======================================================= ERRORS =======================================================
_______________________________________ ERROR collecting tests/test_lsmtool.py _______________________________________
_pytest.runner:139: in __init__
>   ???
_pytest.main:419: in _memocollect
>   ???
_pytest.main:296: in _memoizedcall
>   ???
_pytest.main:419: in <lambda>
>   ???
_pytest.python:445: in collect
>   ???
_pytest.python:1661: in parsefactories
>   ???
_pytest.python:247: in fget
>   ???
_pytest.python:442: in _getobj
>   ???
_pytest.main:296: in _memoizedcall
>   ???
_pytest.python:451: in _importtestmodule
>   ???
py._path.local:620: in pyimport
>   ???
<frozen importlib._bootstrap>:969: in _find_and_load
>   ???
<frozen importlib._bootstrap>:954: in _find_and_load_unlocked
>   ???
<frozen importlib._bootstrap>:892: in _find_spec
>   ???
<frozen importlib._bootstrap>:873: in _find_spec_legacy
>   ???
_pytest.assertion.rewrite:137: in find_module
>   ???
_pytest.assertion.rewrite:269: in _rewrite_test
>   ???
_pytest.assertion.rewrite:322: in rewrite_asserts
>   ???
_pytest.assertion.rewrite:436: in run
>   ???
/usr/lib/python3.5/ast.py:245: in visit
>       return visitor(node)
_pytest.assertion.rewrite:514: in visit_Assert
>   ???
/usr/lib/python3.5/ast.py:245: in visit
>       return visitor(node)
_pytest.assertion.rewrite:601: in visit_Call
>   ???
/usr/lib/python3.5/ast.py:245: in visit
>       return visitor(node)
_pytest.assertion.rewrite:631: in visit_Attribute
>   ???
/usr/lib/python3.5/ast.py:245: in visit
>       return visitor(node)
_pytest.assertion.rewrite:631: in visit_Attribute
>   ???
/usr/lib/python3.5/ast.py:245: in visit
>       return visitor(node)
_pytest.assertion.rewrite:544: in visit_Name
>   ???
E   TypeError: Call constructor takes either 0 or 3 positional arguments
============================================== 1 error in 0.15 seconds ===============================================
```

**Comment by darafferty** [comment] 2018-05-04 08:06
This looks to be fixed in the latest release (at least, I can't reproduce it on my machine): 

```
========================================================================================== test session starts ===========================================================================================
platform darwin -- Python 3.6.5, pytest-3.5.1, py-1.5.3, pluggy-0.6.0
collected 13 items                                                                                                                                                                                       

tests/test_lsmtool.py .............                                                                                                                                                                [100%]

======================================================================================= 13 passed in 15.02 seconds =======================================================================================
```

Please reopen this issue if not.

**Closed by darafferty** 2018-05-04 08:06 UTC
